networks:
  network:

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: exocbt_app
    ports:
      - 80:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    networks:
      - network
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: exocbt_db
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - network
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
